<?php
/**
 * JwkApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Scottbass3\Hydra\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs.
 *
 * The version of the OpenAPI document: v25.4.0
 * Contact: hi@ory.sh
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Scottbass3\Hydra\Client\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Scottbass3\Hydra\Client\ApiException;
use Scottbass3\Hydra\Client\Configuration;
use Scottbass3\Hydra\Client\DebugPlugin;
use Scottbass3\Hydra\Client\HeaderSelector;
use Scottbass3\Hydra\Client\FormDataProcessor;
use Scottbass3\Hydra\Client\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * JwkApi Class Doc Comment
 *
 * @category Class
 * @package  Scottbass3\Hydra\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JwkApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('http://localhost');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createJsonWebKeySet
     *
     * Create JSON Web Key
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\CreateJsonWebKeySet $createJsonWebKeySet createJsonWebKeySet (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\JsonWebKeySet|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function createJsonWebKeySet($set, $createJsonWebKeySet)
    {
        list($response) = $this->createJsonWebKeySetWithHttpInfo($set, $createJsonWebKeySet);
        return $response;
    }

    /**
     * Operation createJsonWebKeySetWithHttpInfo
     *
     * Create JSON Web Key
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\CreateJsonWebKeySet $createJsonWebKeySet (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\JsonWebKeySet|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function createJsonWebKeySetWithHttpInfo($set, $createJsonWebKeySet)
    {
        $request = $this->createJsonWebKeySetRequest($set, $createJsonWebKeySet);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createJsonWebKeySetAsync
     *
     * Create JSON Web Key
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\CreateJsonWebKeySet $createJsonWebKeySet (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function createJsonWebKeySetAsync($set, $createJsonWebKeySet)
    {
        return $this->createJsonWebKeySetAsyncWithHttpInfo($set, $createJsonWebKeySet)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createJsonWebKeySetAsyncWithHttpInfo
     *
     * Create JSON Web Key
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\CreateJsonWebKeySet $createJsonWebKeySet (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function createJsonWebKeySetAsyncWithHttpInfo($set, $createJsonWebKeySet)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\JsonWebKeySet';
        $request = $this->createJsonWebKeySetRequest($set, $createJsonWebKeySet);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'createJsonWebKeySet'
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\CreateJsonWebKeySet $createJsonWebKeySet (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function createJsonWebKeySetRequest($set, $createJsonWebKeySet)
    {
        // verify the required parameter 'set' is set
        if ($set === null || (is_array($set) && count($set) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $set when calling createJsonWebKeySet'
            );
        }
        // verify the required parameter 'createJsonWebKeySet' is set
        if ($createJsonWebKeySet === null || (is_array($createJsonWebKeySet) && count($createJsonWebKeySet) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $createJsonWebKeySet when calling createJsonWebKeySet'
            );
        }

        $resourcePath = '/admin/keys/{set}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($set !== null) {
            $resourcePath = str_replace(
                '{' . 'set' . '}',
                ObjectSerializer::toPathValue($set),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($createJsonWebKeySet)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($createJsonWebKeySet));
            } else {
                $httpBody = $createJsonWebKeySet;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation deleteJsonWebKey
     *
     * Delete JSON Web Key
     *
     * @param  string $set The JSON Web Key Set (required)
     * @param  string $kid The JSON Web Key ID (kid) (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteJsonWebKey($set, $kid)
    {
        $this->deleteJsonWebKeyWithHttpInfo($set, $kid);
    }

    /**
     * Operation deleteJsonWebKeyWithHttpInfo
     *
     * Delete JSON Web Key
     *
     * @param  string $set The JSON Web Key Set (required)
     * @param  string $kid The JSON Web Key ID (kid) (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteJsonWebKeyWithHttpInfo($set, $kid)
    {
        $request = $this->deleteJsonWebKeyRequest($set, $kid);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteJsonWebKeyAsync
     *
     * Delete JSON Web Key
     *
     * @param  string $set The JSON Web Key Set (required)
     * @param  string $kid The JSON Web Key ID (kid) (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deleteJsonWebKeyAsync($set, $kid)
    {
        return $this->deleteJsonWebKeyAsyncWithHttpInfo($set, $kid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteJsonWebKeyAsyncWithHttpInfo
     *
     * Delete JSON Web Key
     *
     * @param  string $set The JSON Web Key Set (required)
     * @param  string $kid The JSON Web Key ID (kid) (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deleteJsonWebKeyAsyncWithHttpInfo($set, $kid)
    {
        $returnType = '';
        $request = $this->deleteJsonWebKeyRequest($set, $kid);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteJsonWebKey'
     *
     * @param  string $set The JSON Web Key Set (required)
     * @param  string $kid The JSON Web Key ID (kid) (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function deleteJsonWebKeyRequest($set, $kid)
    {
        // verify the required parameter 'set' is set
        if ($set === null || (is_array($set) && count($set) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $set when calling deleteJsonWebKey'
            );
        }
        // verify the required parameter 'kid' is set
        if ($kid === null || (is_array($kid) && count($kid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kid when calling deleteJsonWebKey'
            );
        }

        $resourcePath = '/admin/keys/{set}/{kid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($set !== null) {
            $resourcePath = str_replace(
                '{' . 'set' . '}',
                ObjectSerializer::toPathValue($set),
                $resourcePath
            );
        }
        // path params
        if ($kid !== null) {
            $resourcePath = str_replace(
                '{' . 'kid' . '}',
                ObjectSerializer::toPathValue($kid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('DELETE', $uri, $headers, $httpBody);
    }

    /**
     * Operation deleteJsonWebKeySet
     *
     * Delete JSON Web Key Set
     *
     * @param  string $set The JSON Web Key Set (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteJsonWebKeySet($set)
    {
        $this->deleteJsonWebKeySetWithHttpInfo($set);
    }

    /**
     * Operation deleteJsonWebKeySetWithHttpInfo
     *
     * Delete JSON Web Key Set
     *
     * @param  string $set The JSON Web Key Set (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteJsonWebKeySetWithHttpInfo($set)
    {
        $request = $this->deleteJsonWebKeySetRequest($set);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteJsonWebKeySetAsync
     *
     * Delete JSON Web Key Set
     *
     * @param  string $set The JSON Web Key Set (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deleteJsonWebKeySetAsync($set)
    {
        return $this->deleteJsonWebKeySetAsyncWithHttpInfo($set)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteJsonWebKeySetAsyncWithHttpInfo
     *
     * Delete JSON Web Key Set
     *
     * @param  string $set The JSON Web Key Set (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deleteJsonWebKeySetAsyncWithHttpInfo($set)
    {
        $returnType = '';
        $request = $this->deleteJsonWebKeySetRequest($set);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteJsonWebKeySet'
     *
     * @param  string $set The JSON Web Key Set (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function deleteJsonWebKeySetRequest($set)
    {
        // verify the required parameter 'set' is set
        if ($set === null || (is_array($set) && count($set) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $set when calling deleteJsonWebKeySet'
            );
        }

        $resourcePath = '/admin/keys/{set}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($set !== null) {
            $resourcePath = str_replace(
                '{' . 'set' . '}',
                ObjectSerializer::toPathValue($set),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('DELETE', $uri, $headers, $httpBody);
    }

    /**
     * Operation getJsonWebKey
     *
     * Get JSON Web Key
     *
     * @param  string $set JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\JsonWebKeySet|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function getJsonWebKey($set, $kid)
    {
        list($response) = $this->getJsonWebKeyWithHttpInfo($set, $kid);
        return $response;
    }

    /**
     * Operation getJsonWebKeyWithHttpInfo
     *
     * Get JSON Web Key
     *
     * @param  string $set JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\JsonWebKeySet|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function getJsonWebKeyWithHttpInfo($set, $kid)
    {
        $request = $this->getJsonWebKeyRequest($set, $kid);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getJsonWebKeyAsync
     *
     * Get JSON Web Key
     *
     * @param  string $set JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getJsonWebKeyAsync($set, $kid)
    {
        return $this->getJsonWebKeyAsyncWithHttpInfo($set, $kid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getJsonWebKeyAsyncWithHttpInfo
     *
     * Get JSON Web Key
     *
     * @param  string $set JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getJsonWebKeyAsyncWithHttpInfo($set, $kid)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\JsonWebKeySet';
        $request = $this->getJsonWebKeyRequest($set, $kid);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getJsonWebKey'
     *
     * @param  string $set JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getJsonWebKeyRequest($set, $kid)
    {
        // verify the required parameter 'set' is set
        if ($set === null || (is_array($set) && count($set) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $set when calling getJsonWebKey'
            );
        }
        // verify the required parameter 'kid' is set
        if ($kid === null || (is_array($kid) && count($kid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kid when calling getJsonWebKey'
            );
        }

        $resourcePath = '/admin/keys/{set}/{kid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($set !== null) {
            $resourcePath = str_replace(
                '{' . 'set' . '}',
                ObjectSerializer::toPathValue($set),
                $resourcePath
            );
        }
        // path params
        if ($kid !== null) {
            $resourcePath = str_replace(
                '{' . 'kid' . '}',
                ObjectSerializer::toPathValue($kid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getJsonWebKeySet
     *
     * Retrieve a JSON Web Key Set
     *
     * @param  string $set JSON Web Key Set ID (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\JsonWebKeySet|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function getJsonWebKeySet($set)
    {
        list($response) = $this->getJsonWebKeySetWithHttpInfo($set);
        return $response;
    }

    /**
     * Operation getJsonWebKeySetWithHttpInfo
     *
     * Retrieve a JSON Web Key Set
     *
     * @param  string $set JSON Web Key Set ID (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\JsonWebKeySet|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function getJsonWebKeySetWithHttpInfo($set)
    {
        $request = $this->getJsonWebKeySetRequest($set);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getJsonWebKeySetAsync
     *
     * Retrieve a JSON Web Key Set
     *
     * @param  string $set JSON Web Key Set ID (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getJsonWebKeySetAsync($set)
    {
        return $this->getJsonWebKeySetAsyncWithHttpInfo($set)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getJsonWebKeySetAsyncWithHttpInfo
     *
     * Retrieve a JSON Web Key Set
     *
     * @param  string $set JSON Web Key Set ID (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getJsonWebKeySetAsyncWithHttpInfo($set)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\JsonWebKeySet';
        $request = $this->getJsonWebKeySetRequest($set);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getJsonWebKeySet'
     *
     * @param  string $set JSON Web Key Set ID (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getJsonWebKeySetRequest($set)
    {
        // verify the required parameter 'set' is set
        if ($set === null || (is_array($set) && count($set) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $set when calling getJsonWebKeySet'
            );
        }

        $resourcePath = '/admin/keys/{set}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($set !== null) {
            $resourcePath = str_replace(
                '{' . 'set' . '}',
                ObjectSerializer::toPathValue($set),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation setJsonWebKey
     *
     * Set JSON Web Key
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKey $jsonWebKey jsonWebKey (optional)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\JsonWebKey|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function setJsonWebKey($set, $kid, $jsonWebKey = null)
    {
        list($response) = $this->setJsonWebKeyWithHttpInfo($set, $kid, $jsonWebKey);
        return $response;
    }

    /**
     * Operation setJsonWebKeyWithHttpInfo
     *
     * Set JSON Web Key
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKey $jsonWebKey (optional)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\JsonWebKey|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function setJsonWebKeyWithHttpInfo($set, $kid, $jsonWebKey = null)
    {
        $request = $this->setJsonWebKeyRequest($set, $kid, $jsonWebKey);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\JsonWebKey',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\JsonWebKey',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\JsonWebKey',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation setJsonWebKeyAsync
     *
     * Set JSON Web Key
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKey $jsonWebKey (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function setJsonWebKeyAsync($set, $kid, $jsonWebKey = null)
    {
        return $this->setJsonWebKeyAsyncWithHttpInfo($set, $kid, $jsonWebKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation setJsonWebKeyAsyncWithHttpInfo
     *
     * Set JSON Web Key
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKey $jsonWebKey (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function setJsonWebKeyAsyncWithHttpInfo($set, $kid, $jsonWebKey = null)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\JsonWebKey';
        $request = $this->setJsonWebKeyRequest($set, $kid, $jsonWebKey);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'setJsonWebKey'
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  string $kid JSON Web Key ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKey $jsonWebKey (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function setJsonWebKeyRequest($set, $kid, $jsonWebKey = null)
    {
        // verify the required parameter 'set' is set
        if ($set === null || (is_array($set) && count($set) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $set when calling setJsonWebKey'
            );
        }
        // verify the required parameter 'kid' is set
        if ($kid === null || (is_array($kid) && count($kid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kid when calling setJsonWebKey'
            );
        }

        $resourcePath = '/admin/keys/{set}/{kid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($set !== null) {
            $resourcePath = str_replace(
                '{' . 'set' . '}',
                ObjectSerializer::toPathValue($set),
                $resourcePath
            );
        }
        // path params
        if ($kid !== null) {
            $resourcePath = str_replace(
                '{' . 'kid' . '}',
                ObjectSerializer::toPathValue($kid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($jsonWebKey)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($jsonWebKey));
            } else {
                $httpBody = $jsonWebKey;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }

    /**
     * Operation setJsonWebKeySet
     *
     * Update a JSON Web Key Set
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKeySet $jsonWebKeySet jsonWebKeySet (optional)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\JsonWebKeySet|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function setJsonWebKeySet($set, $jsonWebKeySet = null)
    {
        list($response) = $this->setJsonWebKeySetWithHttpInfo($set, $jsonWebKeySet);
        return $response;
    }

    /**
     * Operation setJsonWebKeySetWithHttpInfo
     *
     * Update a JSON Web Key Set
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKeySet $jsonWebKeySet (optional)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\JsonWebKeySet|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function setJsonWebKeySetWithHttpInfo($set, $jsonWebKeySet = null)
    {
        $request = $this->setJsonWebKeySetRequest($set, $jsonWebKeySet);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\JsonWebKeySet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation setJsonWebKeySetAsync
     *
     * Update a JSON Web Key Set
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKeySet $jsonWebKeySet (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function setJsonWebKeySetAsync($set, $jsonWebKeySet = null)
    {
        return $this->setJsonWebKeySetAsyncWithHttpInfo($set, $jsonWebKeySet)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation setJsonWebKeySetAsyncWithHttpInfo
     *
     * Update a JSON Web Key Set
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKeySet $jsonWebKeySet (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function setJsonWebKeySetAsyncWithHttpInfo($set, $jsonWebKeySet = null)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\JsonWebKeySet';
        $request = $this->setJsonWebKeySetRequest($set, $jsonWebKeySet);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'setJsonWebKeySet'
     *
     * @param  string $set The JSON Web Key Set ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\JsonWebKeySet $jsonWebKeySet (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function setJsonWebKeySetRequest($set, $jsonWebKeySet = null)
    {
        // verify the required parameter 'set' is set
        if ($set === null || (is_array($set) && count($set) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $set when calling setJsonWebKeySet'
            );
        }

        $resourcePath = '/admin/keys/{set}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($set !== null) {
            $resourcePath = str_replace(
                '{' . 'set' . '}',
                ObjectSerializer::toPathValue($set),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($jsonWebKeySet)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($jsonWebKeySet));
            } else {
                $httpBody = $jsonWebKeySet;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }


    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
