<?php
/**
 * OidcApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Scottbass3\Hydra\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs.
 *
 * The version of the OpenAPI document: v25.4.0
 * Contact: hi@ory.sh
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Scottbass3\Hydra\Client\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Scottbass3\Hydra\Client\ApiException;
use Scottbass3\Hydra\Client\Configuration;
use Scottbass3\Hydra\Client\DebugPlugin;
use Scottbass3\Hydra\Client\HeaderSelector;
use Scottbass3\Hydra\Client\FormDataProcessor;
use Scottbass3\Hydra\Client\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * OidcApi Class Doc Comment
 *
 * @category Class
 * @package  Scottbass3\Hydra\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OidcApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('http://localhost');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createOidcDynamicClient
     *
     * Register OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client Dynamic Client Registration Request Body (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\OAuth2Client|\Scottbass3\Hydra\Client\Model\ErrorOAuth2|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function createOidcDynamicClient($oAuth2Client)
    {
        list($response) = $this->createOidcDynamicClientWithHttpInfo($oAuth2Client);
        return $response;
    }

    /**
     * Operation createOidcDynamicClientWithHttpInfo
     *
     * Register OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client Dynamic Client Registration Request Body (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\OAuth2Client|\Scottbass3\Hydra\Client\Model\ErrorOAuth2|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function createOidcDynamicClientWithHttpInfo($oAuth2Client)
    {
        $request = $this->createOidcDynamicClientRequest($oAuth2Client);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createOidcDynamicClientAsync
     *
     * Register OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client Dynamic Client Registration Request Body (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function createOidcDynamicClientAsync($oAuth2Client)
    {
        return $this->createOidcDynamicClientAsyncWithHttpInfo($oAuth2Client)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createOidcDynamicClientAsyncWithHttpInfo
     *
     * Register OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client Dynamic Client Registration Request Body (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function createOidcDynamicClientAsyncWithHttpInfo($oAuth2Client)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\OAuth2Client';
        $request = $this->createOidcDynamicClientRequest($oAuth2Client);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'createOidcDynamicClient'
     *
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client Dynamic Client Registration Request Body (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function createOidcDynamicClientRequest($oAuth2Client)
    {
        // verify the required parameter 'oAuth2Client' is set
        if ($oAuth2Client === null || (is_array($oAuth2Client) && count($oAuth2Client) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $oAuth2Client when calling createOidcDynamicClient'
            );
        }

        $resourcePath = '/oauth2/register';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($oAuth2Client)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($oAuth2Client));
            } else {
                $httpBody = $oAuth2Client;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation createVerifiableCredential
     *
     * Issues a Verifiable Credential
     *
     * @param  \Scottbass3\Hydra\Client\Model\CreateVerifiableCredentialRequestBody $createVerifiableCredentialRequestBody createVerifiableCredentialRequestBody (optional)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\VerifiableCredentialResponse|\Scottbass3\Hydra\Client\Model\VerifiableCredentialPrimingResponse|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function createVerifiableCredential($createVerifiableCredentialRequestBody = null)
    {
        list($response) = $this->createVerifiableCredentialWithHttpInfo($createVerifiableCredentialRequestBody);
        return $response;
    }

    /**
     * Operation createVerifiableCredentialWithHttpInfo
     *
     * Issues a Verifiable Credential
     *
     * @param  \Scottbass3\Hydra\Client\Model\CreateVerifiableCredentialRequestBody $createVerifiableCredentialRequestBody (optional)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\VerifiableCredentialResponse|\Scottbass3\Hydra\Client\Model\VerifiableCredentialPrimingResponse|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function createVerifiableCredentialWithHttpInfo($createVerifiableCredentialRequestBody = null)
    {
        $request = $this->createVerifiableCredentialRequest($createVerifiableCredentialRequestBody);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\VerifiableCredentialResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\VerifiableCredentialPrimingResponse',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\VerifiableCredentialResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\VerifiableCredentialResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\VerifiableCredentialPrimingResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createVerifiableCredentialAsync
     *
     * Issues a Verifiable Credential
     *
     * @param  \Scottbass3\Hydra\Client\Model\CreateVerifiableCredentialRequestBody $createVerifiableCredentialRequestBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function createVerifiableCredentialAsync($createVerifiableCredentialRequestBody = null)
    {
        return $this->createVerifiableCredentialAsyncWithHttpInfo($createVerifiableCredentialRequestBody)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createVerifiableCredentialAsyncWithHttpInfo
     *
     * Issues a Verifiable Credential
     *
     * @param  \Scottbass3\Hydra\Client\Model\CreateVerifiableCredentialRequestBody $createVerifiableCredentialRequestBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function createVerifiableCredentialAsyncWithHttpInfo($createVerifiableCredentialRequestBody = null)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\VerifiableCredentialResponse';
        $request = $this->createVerifiableCredentialRequest($createVerifiableCredentialRequestBody);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'createVerifiableCredential'
     *
     * @param  \Scottbass3\Hydra\Client\Model\CreateVerifiableCredentialRequestBody $createVerifiableCredentialRequestBody (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function createVerifiableCredentialRequest($createVerifiableCredentialRequestBody = null)
    {

        $resourcePath = '/credentials';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($createVerifiableCredentialRequestBody)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($createVerifiableCredentialRequestBody));
            } else {
                $httpBody = $createVerifiableCredentialRequestBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation deleteOidcDynamicClient
     *
     * Delete OAuth 2.0 Client using the OpenID Dynamic Client Registration Management Protocol
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteOidcDynamicClient($id)
    {
        $this->deleteOidcDynamicClientWithHttpInfo($id);
    }

    /**
     * Operation deleteOidcDynamicClientWithHttpInfo
     *
     * Delete OAuth 2.0 Client using the OpenID Dynamic Client Registration Management Protocol
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteOidcDynamicClientWithHttpInfo($id)
    {
        $request = $this->deleteOidcDynamicClientRequest($id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\GenericError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteOidcDynamicClientAsync
     *
     * Delete OAuth 2.0 Client using the OpenID Dynamic Client Registration Management Protocol
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deleteOidcDynamicClientAsync($id)
    {
        return $this->deleteOidcDynamicClientAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteOidcDynamicClientAsyncWithHttpInfo
     *
     * Delete OAuth 2.0 Client using the OpenID Dynamic Client Registration Management Protocol
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deleteOidcDynamicClientAsyncWithHttpInfo($id)
    {
        $returnType = '';
        $request = $this->deleteOidcDynamicClientRequest($id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteOidcDynamicClient'
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function deleteOidcDynamicClientRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteOidcDynamicClient'
            );
        }

        $resourcePath = '/oauth2/register/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('DELETE', $uri, $headers, $httpBody);
    }

    /**
     * Operation discoverOidcConfiguration
     *
     * OpenID Connect Discovery
     *
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\OidcConfiguration|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function discoverOidcConfiguration()
    {
        list($response) = $this->discoverOidcConfigurationWithHttpInfo();
        return $response;
    }

    /**
     * Operation discoverOidcConfigurationWithHttpInfo
     *
     * OpenID Connect Discovery
     *
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\OidcConfiguration|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function discoverOidcConfigurationWithHttpInfo()
    {
        $request = $this->discoverOidcConfigurationRequest();

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\OidcConfiguration',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\OidcConfiguration',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\OidcConfiguration',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation discoverOidcConfigurationAsync
     *
     * OpenID Connect Discovery
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function discoverOidcConfigurationAsync()
    {
        return $this->discoverOidcConfigurationAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation discoverOidcConfigurationAsyncWithHttpInfo
     *
     * OpenID Connect Discovery
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function discoverOidcConfigurationAsyncWithHttpInfo()
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\OidcConfiguration';
        $request = $this->discoverOidcConfigurationRequest();

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'discoverOidcConfiguration'
     *
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function discoverOidcConfigurationRequest()
    {

        $resourcePath = '/.well-known/openid-configuration';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getOidcDynamicClient
     *
     * Get OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\OAuth2Client|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function getOidcDynamicClient($id)
    {
        list($response) = $this->getOidcDynamicClientWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getOidcDynamicClientWithHttpInfo
     *
     * Get OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\OAuth2Client|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOidcDynamicClientWithHttpInfo($id)
    {
        $request = $this->getOidcDynamicClientRequest($id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOidcDynamicClientAsync
     *
     * Get OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getOidcDynamicClientAsync($id)
    {
        return $this->getOidcDynamicClientAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOidcDynamicClientAsyncWithHttpInfo
     *
     * Get OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getOidcDynamicClientAsyncWithHttpInfo($id)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\OAuth2Client';
        $request = $this->getOidcDynamicClientRequest($id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOidcDynamicClient'
     *
     * @param  string $id The id of the OAuth 2.0 Client. (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getOidcDynamicClientRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getOidcDynamicClient'
            );
        }

        $resourcePath = '/oauth2/register/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getOidcUserInfo
     *
     * OpenID Connect Userinfo
     *
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\OidcUserInfo|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function getOidcUserInfo()
    {
        list($response) = $this->getOidcUserInfoWithHttpInfo();
        return $response;
    }

    /**
     * Operation getOidcUserInfoWithHttpInfo
     *
     * OpenID Connect Userinfo
     *
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\OidcUserInfo|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOidcUserInfoWithHttpInfo()
    {
        $request = $this->getOidcUserInfoRequest();

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\OidcUserInfo',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\OidcUserInfo',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\OidcUserInfo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOidcUserInfoAsync
     *
     * OpenID Connect Userinfo
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getOidcUserInfoAsync()
    {
        return $this->getOidcUserInfoAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOidcUserInfoAsyncWithHttpInfo
     *
     * OpenID Connect Userinfo
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getOidcUserInfoAsyncWithHttpInfo()
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\OidcUserInfo';
        $request = $this->getOidcUserInfoRequest();

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOidcUserInfo'
     *
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getOidcUserInfoRequest()
    {

        $resourcePath = '/userinfo';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation revokeOidcSession
     *
     * OpenID Connect Front- and Back-channel Enabled Logout
     *
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function revokeOidcSession()
    {
        $this->revokeOidcSessionWithHttpInfo();
    }

    /**
     * Operation revokeOidcSessionWithHttpInfo
     *
     * OpenID Connect Front- and Back-channel Enabled Logout
     *
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function revokeOidcSessionWithHttpInfo()
    {
        $request = $this->revokeOidcSessionRequest();

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation revokeOidcSessionAsync
     *
     * OpenID Connect Front- and Back-channel Enabled Logout
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function revokeOidcSessionAsync()
    {
        return $this->revokeOidcSessionAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation revokeOidcSessionAsyncWithHttpInfo
     *
     * OpenID Connect Front- and Back-channel Enabled Logout
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function revokeOidcSessionAsyncWithHttpInfo()
    {
        $returnType = '';
        $request = $this->revokeOidcSessionRequest();

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'revokeOidcSession'
     *
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function revokeOidcSessionRequest()
    {

        $resourcePath = '/oauth2/sessions/logout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation setOidcDynamicClient
     *
     * Set OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  string $id OAuth 2.0 Client ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client OAuth 2.0 Client Request Body (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Scottbass3\Hydra\Client\Model\OAuth2Client|\Scottbass3\Hydra\Client\Model\ErrorOAuth2|\Scottbass3\Hydra\Client\Model\ErrorOAuth2
     */
    public function setOidcDynamicClient($id, $oAuth2Client)
    {
        list($response) = $this->setOidcDynamicClientWithHttpInfo($id, $oAuth2Client);
        return $response;
    }

    /**
     * Operation setOidcDynamicClientWithHttpInfo
     *
     * Set OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  string $id OAuth 2.0 Client ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client OAuth 2.0 Client Request Body (required)
     *
     * @throws \Scottbass3\Hydra\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Scottbass3\Hydra\Client\Model\OAuth2Client|\Scottbass3\Hydra\Client\Model\ErrorOAuth2|\Scottbass3\Hydra\Client\Model\ErrorOAuth2, HTTP status code, HTTP response headers (array of strings)
     */
    public function setOidcDynamicClientWithHttpInfo($id, $oAuth2Client)
    {
        $request = $this->setOidcDynamicClientRequest($id, $oAuth2Client);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\OAuth2Client',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Scottbass3\Hydra\Client\Model\ErrorOAuth2',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation setOidcDynamicClientAsync
     *
     * Set OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  string $id OAuth 2.0 Client ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client OAuth 2.0 Client Request Body (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function setOidcDynamicClientAsync($id, $oAuth2Client)
    {
        return $this->setOidcDynamicClientAsyncWithHttpInfo($id, $oAuth2Client)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation setOidcDynamicClientAsyncWithHttpInfo
     *
     * Set OAuth2 Client using OpenID Dynamic Client Registration
     *
     * @param  string $id OAuth 2.0 Client ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client OAuth 2.0 Client Request Body (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function setOidcDynamicClientAsyncWithHttpInfo($id, $oAuth2Client)
    {
        $returnType = '\Scottbass3\Hydra\Client\Model\OAuth2Client';
        $request = $this->setOidcDynamicClientRequest($id, $oAuth2Client);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'setOidcDynamicClient'
     *
     * @param  string $id OAuth 2.0 Client ID (required)
     * @param  \Scottbass3\Hydra\Client\Model\OAuth2Client $oAuth2Client OAuth 2.0 Client Request Body (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function setOidcDynamicClientRequest($id, $oAuth2Client)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling setOidcDynamicClient'
            );
        }
        // verify the required parameter 'oAuth2Client' is set
        if ($oAuth2Client === null || (is_array($oAuth2Client) && count($oAuth2Client) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $oAuth2Client when calling setOidcDynamicClient'
            );
        }

        $resourcePath = '/oauth2/register/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($oAuth2Client)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($oAuth2Client));
            } else {
                $httpBody = $oAuth2Client;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }


    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
